name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  echo:
    runs-on: ubuntu-22.04
    steps:
      - uses: RuffaloLavoisier/Builvery@main
        with:
          title: test demo repository